adam_gamma: 0.5
adam_lr: 0.001
adam_step: 20
centroids: centroids_0
channels: 3
data: G:\Python\python_work\conda_test\metric_learning_few_shots\prototypical-networks-few-shot-learning-main\datasets/officehome
device: cuda
episodes: 200
eval_each: 1
imgsz: 64
iterations: 100
metric: euclidean
mode: train
model: null
num_way: 30
patience: 10
patience_delta: 0.01
query: 15
save_period: 5
shot: 5
val_num_way: 5
